### ISSUE TITLE
add portfolio

### ISSUE THREAD

**Issue by AustriaChristian0202** [AustriaChristian0202/IPT2-Case-Study#5]
Created an Issue for our project, post your comments on this issue.

**Comment by AustriaChristian0202** [comment]
Added folder for my portfolio, pull request and merge it to the main branch including my index file

**Comment by AustriaChristian0202** [comment]
Completed my documentation

**Comment by ChumSantos14** [comment]
Santos' Portfolio now uploaded into Santos-branch and is merged with main branch via merge pull request successfully.

**Comment by CarlPalasigue** [comment]
palasigue-branch added and portfolio files

**Comment by AlanoChristian0195** [comment]
done uploading and documenting portofolio for alano-branch

**Comment by AustriaChristian0202** [comment]
All participants have already uploaded their Portfolio using their own branch to merge into the main branch
